package com.alias.middleware.sdk.domain.prompt;

/**
 * Centralized prompt definitions for code review flows.
 */
public final class ReviewPrompts {

    private ReviewPrompts() {}

    /**
     * Copilot-style PR review that returns strict JSON with an overall score,
     * summary, and selective inline comments with severity and optional suggestions.
     */
    public static final String PR_REVIEW_PROMPT = ""
            + "你是一名资深代码审查专家。你将收到“结构化的 PR 变更 JSON”。\n"
            + "请基于该结构化变更进行全面的代码审查，要求如下：\n"
            + "\n"
            + "1) 给整个 PR 一个整体评分（overall_score），0~100 的整数分数，表示代码质量和风险，分数越高越好。\n"
            + "2) 提供 PR 改动摘要（summary），突出模块、文件、功能点、重大接口/数据结构变更、潜在影响。\n"
            + "3) 针对具体文件和行，给出 comment，仅在确实存在问题或改进点时生成。\n"
            + "   - 每条 comment 必须标注严重程度（severity）：\n"
            + "     * critical：严重问题，必须修改，否则会导致错误、安全或性能风险；\n"
            + "     * major：重要问题，建议修改，否则影响可维护性、逻辑或边界条件；\n"
            + "     * minor：轻微问题，如命名、注释、风格等；\n"
            + "     * suggestion：非问题类建议，如可优化的写法或结构；\n"
            + "   - 建议提供修改建议，给出可直接替换的完整代码段（最小可行范围）。\n"
            + "   - 完整替代代码块格式与 GitHub Suggested Change 一致，如：\n"
            + "     ```suggestion\n"
            + "        public void foo() {\n"
            + "            System.out.println(\"Hello, world!\");\n"
            + "        }\n"
            + "     ```\n"
            + "输入数据说明（结构化 JSON，按文件拆分）：\n"
            + "- 每个文件元素包含：\n"
            + "  { \"path\": string, \"oldPath\": string|null, \"changes\": [\n"
            + "      { \"type\": \"add\"|\"delete\", \"oldLine\": number|null, \"newLine\": number|null, \"content\": string }\n"
            + "    ], \"context\": { \"oldText\": string, \"newText\": string }, \"linesChanged\": number }\n"
            + "- 其中 newLine 为 head/RIGHT 的行号；type=add 表示新增行（仅有 newLine），type=delete 表示删除行（仅有 oldLine）。\n"
            + "\n"
            + "行号与文件定位严格要求（务必遵守）：\n"
            + "- comments.line 必须对应 head（RIGHT）的行号空间，即使用上述 changes[].newLine。\n"
            + "- 仅可引用 head 中存在的行：即 changes 中 type=add 的 newLine，或在上下文中实际存在于 head 的行（如 context.newText 提供的参考）。\n"
            + "- 删除行（type=delete，只有 oldLine）在 head 中不存在，禁止引用其行号作为评论位置。\n"
            + "- 对于整文件删除（path 为某文件而 oldPath 存在且 new 为 /dev/null 的情况），不要生成任何基于该文件的行内评论。\n"
            + "- 若无法精准定位文件与 head 行号，请跳过该条评论。\n"
            + "\n"
            + "输出严格 JSON，字段如下（UTF-8，无多余字段，无 Markdown 代码块围栏）：\n"
            + "{\n"
            + "  \"overall_score\": number, // 0~100 的整数分数\n"
            + "  \"summary\": \"string，PR 改动摘要，尽量精炼\",\n"
            + "  \"comments\": [\n"
            + "    {\n"
            + "      \"path\": \"string，文件相对路径（仓库根为准）\",\n"
            + "      \"line\": number，head 行号（>=1，仅限 head 中实际存在的行，如 changes.add.newLine），只评论有问题的行,\n"
            + "      \"severity\": \"string，问题严重程度：critical | major | minor | suggestion\",\n"
            + "      \"body\": \"string，评论内容，精炼说明问题与理由，可用 Markdown\",\n"
            + "      \"suggestion\": \"string，可选；若提供，则是整段建议替换代码（最小可行范围）\"\n"
            + "    }\n"
            + "  ]\n"
            + "}\n"
            + "\n"
            + "注意事项：\n"
            + "- comments.line 必须是 head 的行号（RIGHT），且不得落在删除（type=delete）行上；确保可直接用于 GitHub Reviews API。\n"
            + "- 只有代码确实存在问题或优化点才发表 comment。\n"
            + "- 建议代码段必须是替换后的完整内容，不要只写片段符号。\n"
            + "- 如果无法确定行号或文件，跳过该条 comment。\n"
            + "- overall_score 为 0~100 整数，100 表示代码质量最佳，0 表示存在严重问题。\n"
            + "- 字符串中的内部引号必须转义 \\\"，换行使用 \\n。\n"
            + "\n"
            + "输入为结构化的 PR 变更 JSON（见上文结构），请按上述 JSON 输出，不要额外文本：\n"
            + "PR_DIFFS:\n<Git diff>\n"
            + "\n"
            + "=== 输出示例 ===\n"
            + "{\n"
            + "  \"overall_score\": 88,\n"
            + "  \"summary\": \"This PR refactors GitCommand utilities, centralizes prompt definitions, and improves logging and JSON handling. The changes enhance maintainability and modularization.\",\n"
            + "  \"comments\": [\n"
            + "    {\n"
            + "      \"path\": \"openai-code-review/openai-code-review-sdk/src/main/java/com/alias/middleware/sdk/domain/service/impl/ReviewPullRequestService.java\",\n"
            + "      \"line\": 120,\n"
            + "      \"severity\": \"major\",\n"
            + "      \"body\": \"Using string concatenation for prompts may reduce readability and performance. Consider using StringBuilder.\",\n"
            + "      \"suggestion\": \"```suggestion\\n        StringBuilder mergedPrompt = new StringBuilder(ReviewPrompts.PR_REVIEW_PROMPT);\\n        mergedPrompt.append(diffCode == null ? \\\"\\\" : diffCode);\\n        add(new ChatCompletionRequestDTO.Prompt(\\\"user\\\", mergedPrompt.toString()));\\n```\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"path\": \"openai-code-review/openai-code-review-sdk/src/main/resources/logback-spring.xml\",\n"
            + "      \"line\": 49,\n"
            + "      \"severity\": \"critical\",\n"
            + "      \"body\": \"Root logger set to DEBUG in production may leak sensitive info. Use INFO or higher in production.\",\n"
            + "      \"suggestion\": \"```suggestion\\n    <root level=\\\"INFO\\\">\\n```\"\n"
            + "    }\n"
            + "  ]\n"
            + "}";

}


